services:
  - type: static
    name: skilltobill-frontend
    env: static
    buildCommand: ""
    publishPath: .
    headers:
      - for: "/*.css"
        values:
          Content-Type: "text/css"
    routes:
      - path: /*
        rewrite: /home.html
